### ISSUE TITLE
Dynamic Content-Type Selection when serving static content could result in Content-Type confusion or KeyErrors

### ISSUE THREAD

**Issue by claudijd** [mozilla/session-invalidation#1]
In reviewing the code here: https://github.com/mozilla/session-invalidation/blob/master/lambda.py#L389-L400

I noticed the possibility for content-type confusion bugs or keyerror outcomes.  I'd recommend the following to address this:

1. Perform the dynamic detection outside of the return block using a .get() operation (this will avoid the KeyError case)
2. Perform an additional check to verify that the dynamically detected content-type is not None, if so, return error_404 (this will avoid the content-type confusion case)

I wasn't able to press these cases in practice due to authentication barriers, and I would like to acknowledge the KeyError case being more likely than content-type confusion, but I think it's worth addressing both cases explicitly to avoid implicit outcomes.

**Comment by chaoticsmol** [comment]
Thanks for the suggestion! This was addressed in c9cfb41fa4027aa1298277dc7c615ab6a6af86df
