### ISSUE TITLE
Echoing user supplied content in 404 responses when serving static could present XSS scenarios

### ISSUE THREAD

**Issue by claudijd** [mozilla/session-invalidation#2]
In reviewing the following code: https://github.com/mozilla/session-invalidation/blob/master/lambda.py#L370-L373

I noticed two things we could improve to reduce our chances of XSS scenarios via 404 responses on serving static content:

1. Avoid echoing the supplied content and favor a generic static response (this will prevent an attacker from getting their content reflected in the response and address XSS scenarios)
2. Consider being explicit about the content-type for error_404, like text/plain (this will prevent the possibility of content-type confusion bugs with an actors browser)

I wasn't able to press these cases in practice due to authentication barriers and I'm not sure what the default content-type is here (possibly HTML/JSON?), but if it is HTML, I'd say the likelihood for XSS possibilities is higher.  Taking both of the recommended steps above should resolve this potential.

**Comment by chaoticsmol** [comment]
This is another great point.  I've addressed it in 3cdda0481b1486f88483c7de9c7272bc4df238fa.
