### ISSUE TITLE
Can trigger internal server error calling /callback without parameters

### ISSUE THREAD

**Issue by claudijd** [mozilla/session-invalidation#4]
Was reviewing this code: https://github.com/mozilla/session-invalidation/blob/master/lambda.py#L249

I noticed that calling just the /callback path can trigger an "Internal Server Error" though it doesn't appear to be explicitly mentioned in the callback method, I wanted to flag this as a possible emergent but unidentified code path.

I'd recommend tracing it out and identifying what is triggering this error and instead providing a helpful response similarly seen when state or code are not supplied, such as "Missing required parameter(s) `code` or `state`".  The reason for doing this is simply heading off emergent code paths, which may lead to future vectors of attacker interest.

**Comment by chaoticsmol** [comment]
This was a really surprising one but I managed to fix it in c83a26a. Thanks!
