### ISSUE TITLE
Echo'ing of arbitrary error responses in a 500 HTML content could present XSS scenarios

### ISSUE THREAD

**Issue by claudijd** [mozilla/session-invalidation#5]
I was reviewing this code: https://github.com/mozilla/session-invalidation/blob/master/lambda.py#L239-L246

I'd recommend two actions here:

1. Use a less dangerous content-type for 500 responses, such as plain (this will reduce the impact of attacker supplied content from being echo'd into the HTML context and result in data being confused as code)
2. Consider not providing detailed error responses in a 500 response, especially in a production context.  I'd advise just being generic "An error occurred" and only surfacing detailed error messages in a development context. (this will fix the data supplied, so it's no longer end user controlled).

**Comment by chaoticsmol** [comment]
Thanks once again! This was just resolved in 84ce3db.
